<?php

namespace App\OpenApi;

/**
 * Tareas (carga diaria / masivo) + informes / dashboard.
 *
 * @OA\Get(path="/api/v1/partes/parametros/duracion-tramo", operationId="partesDuracionTramo", tags={"Partes Tareas"}, summary="Parámetro duración tramo (minutos)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/tareas", operationId="partesTareasList", tags={"Partes Tareas"}, summary="Listar tareas (filtros fecha/cliente/asistente)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="fechaDesde", in="query", @OA\Schema(type="string", format="date")), @OA\Parameter(name="fechaHasta", in="query", @OA\Schema(type="string", format="date")), @OA\Parameter(name="clienteId", in="query", @OA\Schema(type="integer")), @OA\Parameter(name="asistenteId", in="query", @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/tareas/ids", operationId="partesTareasListIds", tags={"Partes Tareas"}, summary="IDs de tareas según filtros (masivo)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas/masivo/set-cerrado", operationId="partesTareasMasivoSetCerrado", tags={"Partes Tareas"}, summary="Cerrar/reabrir tareas en lote", security={{"sanctum":{}},{"tenant":{}}}, @OA\RequestBody(@OA\JsonContent(@OA\Property(property="ids", type="array", @OA\Items(type="integer")), @OA\Property(property="cerrado", type="boolean"))), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas/masivo/actualizar", operationId="partesTareasMasivoActualizar", tags={"Partes Tareas"}, summary="Actualizar campos en lote", security={{"sanctum":{}},{"tenant":{}}}, @OA\RequestBody(@OA\JsonContent(@OA\Property(property="ids", type="array", @OA\Items(type="integer")))), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas/asistente/turn", operationId="partesTareasAsistenteTurn", tags={"Partes Tareas"}, summary="Turno Smart Capture (GEN-03) en carga diaria — propone campos; no persiste", security={{"sanctum":{}},{"tenant":{}}}, @OA\RequestBody(required=true, @OA\JsonContent(@OA\Property(property="contractVersion", type="integer", example=1), @OA\Property(property="message", type="string"), @OA\Property(property="modality", type="string", enum={"texto","audio","imagen"}), @OA\Property(property="credentialId", type="integer"), @OA\Property(property="draftContext", type="object"), @OA\Property(property="pendingChoice", type="object", nullable=true), @OA\Property(property="images", type="array", @OA\Items(type="object")))), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")), @OA\Response(response=409, description="Sin LLM (4201)", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/tareas/{id}", operationId="partesTareasShow", tags={"Partes Tareas"}, summary="Detalle tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas", operationId="partesTareasStore", tags={"Partes Tareas"}, summary="Alta tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Put(path="/api/v1/partes/tareas/{id}", operationId="partesTareasUpdate", tags={"Partes Tareas"}, summary="Actualizar tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/tareas/{id}", operationId="partesTareasDestroy", tags={"Partes Tareas"}, summary="Eliminar tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas/{id}/cerrar", operationId="partesTareasCerrar", tags={"Partes Tareas"}, summary="Cerrar tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tareas/{id}/reabrir", operationId="partesTareasReabrir", tags={"Partes Tareas"}, summary="Reabrir tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/parametros/dashboard", operationId="partesDashboardParametros", tags={"Partes Informes"}, summary="Parámetros del dashboard", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/dashboard", operationId="partesDashboard", tags={"Partes Informes"}, summary="Datos dashboard", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/informes/tareas", operationId="partesInformesTareas", tags={"Partes Informes"}, summary="Informe listado de tareas", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/informes/agrupado", operationId="partesInformesAgrupado", tags={"Partes Informes"}, summary="Informe agrupado", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/informes/paquete-horas", operationId="partesInformesPaqueteHoras", tags={"Partes Informes"}, summary="Informe paquete de horas", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 */
abstract class OpenApiPathsPartesOperacion
{
}
