<?php

namespace App\OpenApi;

/**
 * Maestros Partes (ABM + catálogos lookup).
 *
 * @OA\Get(path="/api/v1/partes/asistentes", operationId="partesAsistentesList", tags={"Partes Maestros"}, summary="Listar asistentes", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="soloActivos", in="query", @OA\Schema(type="boolean")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/asistentes/{id}", operationId="partesAsistentesGet", tags={"Partes Maestros"}, summary="Detalle asistente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/asistentes", operationId="partesAsistentesStore", tags={"Partes Maestros"}, summary="Alta asistente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Put(path="/api/v1/partes/asistentes/{id}", operationId="partesAsistentesUpdate", tags={"Partes Maestros"}, summary="Actualizar asistente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Patch(path="/api/v1/partes/asistentes/{id}/estado", operationId="partesAsistentesPatchEstado", tags={"Partes Maestros"}, summary="Cambiar estado asistente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/asistentes/{id}", operationId="partesAsistentesDelete", tags={"Partes Maestros"}, summary="Eliminar asistente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/clientes", operationId="partesClientesList", tags={"Partes Maestros"}, summary="Listar clientes", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="soloActivos", in="query", @OA\Schema(type="boolean")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/clientes/{id}", operationId="partesClientesGet", tags={"Partes Maestros"}, summary="Detalle cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/clientes", operationId="partesClientesStore", tags={"Partes Maestros"}, summary="Alta cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Put(path="/api/v1/partes/clientes/{id}", operationId="partesClientesUpdate", tags={"Partes Maestros"}, summary="Actualizar cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Patch(path="/api/v1/partes/clientes/{id}/estado", operationId="partesClientesPatchEstado", tags={"Partes Maestros"}, summary="Cambiar estado cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/clientes/{id}", operationId="partesClientesDelete", tags={"Partes Maestros"}, summary="Eliminar cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/clientes/{id}/acceso", operationId="partesClientesSetAcceso", tags={"Partes Maestros"}, summary="Asignar acceso portal cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/clientes/{id}/acceso", operationId="partesClientesRevokeAcceso", tags={"Partes Maestros"}, summary="Revocar acceso portal cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/tipos-cliente", operationId="partesTiposClienteList", tags={"Partes Maestros"}, summary="Listar tipos de cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/tipos-cliente/{id}", operationId="partesTiposClienteGet", tags={"Partes Maestros"}, summary="Detalle tipo cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tipos-cliente", operationId="partesTiposClienteStore", tags={"Partes Maestros"}, summary="Alta tipo cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Put(path="/api/v1/partes/tipos-cliente/{id}", operationId="partesTiposClienteUpdate", tags={"Partes Maestros"}, summary="Actualizar tipo cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Patch(path="/api/v1/partes/tipos-cliente/{id}/estado", operationId="partesTiposClientePatchEstado", tags={"Partes Maestros"}, summary="Cambiar estado tipo cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/tipos-cliente/{id}", operationId="partesTiposClienteDelete", tags={"Partes Maestros"}, summary="Eliminar tipo cliente", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/tipos-tarea", operationId="partesTiposTareaList", tags={"Partes Maestros"}, summary="Listar tipos de tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/tipos-tarea/{id}", operationId="partesTiposTareaGet", tags={"Partes Maestros"}, summary="Detalle tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/tipos-tarea", operationId="partesTiposTareaStore", tags={"Partes Maestros"}, summary="Alta tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Put(path="/api/v1/partes/tipos-tarea/{id}", operationId="partesTiposTareaUpdate", tags={"Partes Maestros"}, summary="Actualizar tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Patch(path="/api/v1/partes/tipos-tarea/{id}/estado", operationId="partesTiposTareaPatchEstado", tags={"Partes Maestros"}, summary="Cambiar estado tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/tipos-tarea/{id}", operationId="partesTiposTareaDelete", tags={"Partes Maestros"}, summary="Eliminar tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/cliente-tipos-tarea", operationId="partesClienteTiposTareaList", tags={"Partes Maestros"}, summary="Listar asignaciones cliente↔tipo tarea", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Post(path="/api/v1/partes/cliente-tipos-tarea", operationId="partesClienteTiposTareaStore", tags={"Partes Maestros"}, summary="Alta asignación", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Delete(path="/api/v1/partes/cliente-tipos-tarea/{id}", operationId="partesClienteTiposTareaDelete", tags={"Partes Maestros"}, summary="Eliminar asignación", security={{"sanctum":{}},{"tenant":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 *
 * @OA\Get(path="/api/v1/partes/catalogos/clientes", operationId="partesCatalogoClientes", tags={"Partes Maestros"}, summary="Catálogo clientes (lookup)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/catalogos/asistentes", operationId="partesCatalogoAsistentes", tags={"Partes Maestros"}, summary="Catálogo asistentes (lookup)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/catalogos/tipos-cliente", operationId="partesCatalogoTiposCliente", tags={"Partes Maestros"}, summary="Catálogo tipos cliente (lookup)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 * @OA\Get(path="/api/v1/partes/catalogos/tipos-tarea", operationId="partesCatalogoTiposTarea", tags={"Partes Maestros"}, summary="Catálogo tipos tarea (lookup)", security={{"sanctum":{}},{"tenant":{}}}, @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/ApiEnvelope")))
 */
abstract class OpenApiPathsPartesMaestros
{
}
