/** Generado desde devextreme/dist/css — regenerar con scripts/gen-dx-theme-urls.mjs */
export const EMPRESA_THEME_CSS_URLS: Record<string, string> = {
  'fluent.blue.dark': '/dx-themes/dx.fluent.blue.dark.css',
  'fluent.blue.dark.compact': '/dx-themes/dx.fluent.blue.dark.compact.css',
  'fluent.blue.light': '/dx-themes/dx.fluent.blue.light.css',
  'fluent.blue.light.compact': '/dx-themes/dx.fluent.blue.light.compact.css',
  'fluent.saas.dark': '/dx-themes/dx.fluent.saas.dark.css',
  'fluent.saas.dark.compact': '/dx-themes/dx.fluent.saas.dark.compact.css',
  'fluent.saas.light': '/dx-themes/dx.fluent.saas.light.css',
  'fluent.saas.light.compact': '/dx-themes/dx.fluent.saas.light.compact.css',
  'generic.carmine': '/dx-themes/dx.carmine.css',
  'generic.carmine.compact': '/dx-themes/dx.carmine.compact.css',
  'generic.contrast': '/dx-themes/dx.contrast.css',
  'generic.contrast.compact': '/dx-themes/dx.contrast.compact.css',
  'generic.dark': '/dx-themes/dx.dark.css',
  'generic.dark.compact': '/dx-themes/dx.dark.compact.css',
  'generic.darkmoon': '/dx-themes/dx.darkmoon.css',
  'generic.darkmoon.compact': '/dx-themes/dx.darkmoon.compact.css',
  'generic.darkviolet': '/dx-themes/dx.darkviolet.css',
  'generic.darkviolet.compact': '/dx-themes/dx.darkviolet.compact.css',
  'generic.greenmist': '/dx-themes/dx.greenmist.css',
  'generic.greenmist.compact': '/dx-themes/dx.greenmist.compact.css',
  'generic.light': '/dx-themes/dx.light.css',
  'generic.light.compact': '/dx-themes/dx.light.compact.css',
  'generic.softblue': '/dx-themes/dx.softblue.css',
  'generic.softblue.compact': '/dx-themes/dx.softblue.compact.css',
  'material.blue.dark': '/dx-themes/dx.material.blue.dark.css',
  'material.blue.dark.compact': '/dx-themes/dx.material.blue.dark.compact.css',
  'material.blue.light': '/dx-themes/dx.material.blue.light.css',
  'material.blue.light.compact': '/dx-themes/dx.material.blue.light.compact.css',
  'material.lime.dark': '/dx-themes/dx.material.lime.dark.css',
  'material.lime.dark.compact': '/dx-themes/dx.material.lime.dark.compact.css',
  'material.lime.light': '/dx-themes/dx.material.lime.light.css',
  'material.lime.light.compact': '/dx-themes/dx.material.lime.light.compact.css',
  'material.orange.dark': '/dx-themes/dx.material.orange.dark.css',
  'material.orange.dark.compact': '/dx-themes/dx.material.orange.dark.compact.css',
  'material.orange.light': '/dx-themes/dx.material.orange.light.css',
  'material.orange.light.compact': '/dx-themes/dx.material.orange.light.compact.css',
  'material.purple.dark': '/dx-themes/dx.material.purple.dark.css',
  'material.purple.dark.compact': '/dx-themes/dx.material.purple.dark.compact.css',
  'material.purple.light': '/dx-themes/dx.material.purple.light.css',
  'material.purple.light.compact': '/dx-themes/dx.material.purple.light.compact.css',
  'material.teal.dark': '/dx-themes/dx.material.teal.dark.css',
  'material.teal.dark.compact': '/dx-themes/dx.material.teal.dark.compact.css',
  'material.teal.light': '/dx-themes/dx.material.teal.light.css',
  'material.teal.light.compact': '/dx-themes/dx.material.teal.light.compact.css',
}

export const EMPRESA_THEME_CSS_KEYS = Object.keys(EMPRESA_THEME_CSS_URLS)
